### ISSUE TITLE
Weight of dense_comb probably not initialized uniformly

### ISSUE THREAD

**Issue by Bernhard-Steindl** [sebastian-hofstaetter/matchmaker#11]
Hi Sebastian,

While reading your code of the tk model, I found that you are initializing the weights of the `dense` layer twice, but the `dense_comb` layer not at all. It looks like you may have missed it for the latter, because the line is just repeated.
I have not checked if it makes any difference, but probably this should be checked.

I hope this issue was helpful. See the code below, where line L73 is the same like L77.

All the best,
Bernhard

https://github.com/sebastian-hofstaetter/transformer-kernel-ranking/blob/e11624befb2431cc7ce5510eb99d43b396ea3f03/matchmaker/models/tk.py#L67-L77

**Comment by sebastian-hofstaetter** [comment]
Hi,
Thanks for the find - we have now a newer version of TK, where this issue is solved (by removing the layer entirely, but unrelated to this issue).
Best,
Sebastian
