### ISSUE TITLE
How can I use it to rank document after the model trainned?

### ISSUE THREAD

**Issue by cktsangal** [sebastian-hofstaetter/matchmaker#8]
I want know how can I feed the input data and get the ranking result from the trained model?

**Comment by sebastian-hofstaetter** [comment]
Hi,
Sorry, for the super late reply - I forgot to monitor the repo. We have now updated the library and especially for dense retrieval we have many evaluation settings (via dense_retrieval.py). If you want to do re-ranking evaluation only you can use the --continue-folder setting of train.py
Best,
Sebastian
